[package]
name = "factorials"
version = "0.1.0"
authors = ["https://oopscenities.net/"]
edition = "2021"
publish = false

# dependencies:
[dependencies]

[[bin]]
name = "factorials"
path = "src/main/rust/main.rs"
